name: TwitterSigns
version: '${project.version}'
main: org.dafy.twittersigns.TwitterSigns
commands:
   Twitter:
    permission-message: "No permission."
    permission: "twittersigns.commands.admin"

